# production configuration

spring:
   config:
      activate:
         on-profile: production
         
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://192.168.0.172:8761/eureka