# development configuration

spring:
   config:
      activate:
         on-profile: development

logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

eureka:
   client:
      registerWithEureka: false
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
