# configuration: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/webdb?charset=utf8
      username: webdb
      password: '{cipher}AQCgLx9cQujFP48kBpjd6Ec922c7jB+lvuBJyOCDZHgOpqA9SlNG/ZDjHRScccHQnRtgBaHxEbyxcx/g9RRIz/zSmS9+xQG1t3EgvRchcUujVU4xmSbwFI3wMKTBCjK8+2mRh1UzBhxOQpj5HjEPbPATrnidtasy0ulzk6KiUxlupx4fljNpYngp25JKgWQTav7yLBMdnM7wGvssrsLSP0k5FNaVIfMaUmkJCsaf6PRFu0dmNAnUYvo4AKQu2NsToFTCmybIUA9GDWk9CmgNTt5DvDw2X52YIrFkMEpRc7aZiu+l1UesX4oNoc2lj3bfdpqlMR2uYVCsl4kFBQKqiaBugUEpcwEGrBU5vURJMm2Vfj99hyqM5hl5HHTvylhzhf0='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            msa:
               service:
                  guestbook:
                     exception: ERROR
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.0.172:8761/eureka